version: '2'
volumes:
  cache:

services:
  librespot:
    build: ./librespot
    network_mode: host
    devices:
      - '/dev/snd:/dev/snd'
    volumes:
      - 'cache:/tmp'

  pidi-spotify:
    build: ./pidi-spotify
    privileged: true
    volumes:
      - 'cache:/tmp'
