FROM balenalib/%%BALENA_MACHINE_NAME%%-alpine-golang:1.15-edge-build as build

WORKDIR /go/src/hook

COPY main.go main.go
RUN go get && go build

FROM balenalib/%%BALENA_MACHINE_NAME%%-alpine:edge-run as run

RUN install_packages -X http://dl-cdn.alpinelinux.org/alpine/edge/testing \
    librespot

WORKDIR /app
COPY --from=build /go/src/hook/hook .

ENTRYPOINT ["/usr/bin/librespot"]
CMD ["--name","pirate","--device","hw:1,0","--onevent","/app/hook"]
